Fix delete() missing self
Silent delete is not actually working because self is not being passed (therefore it doesn't know *what* to delete. This fixes that. 

This is the actual traceback which caused me to notice the bug.
```py
Sep 13 19:17:08 trainerdex-beta-0 python[2319040]: [2020-09-13 19:17:08] [ERROR] red: Exception in command 'profile edit visible'
Sep 13 19:17:08 trainerdex-beta-0 python[2319040]: Traceback (most recent call last):
Sep 13 19:17:08 trainerdex-beta-0 python[2319040]:   File "/opt/DiscordBot/env/lib/python3.8/site-packages/discord/ext/commands/core.py", line 85, in wrapped
Sep 13 19:17:08 trainerdex-beta-0 python[2319040]:     ret = await coro(*args, **kwargs)
Sep 13 19:17:08 trainerdex-beta-0 python[2319040]:   File "/opt/DiscordBot/tdx/profile.py", line 210, in profile__edit__visible
Sep 13 19:17:08 trainerdex-beta-0 python[2319040]:     await ctx.send(
Sep 13 19:17:08 trainerdex-beta-0 python[2319040]:   File "/opt/DiscordBot/env/lib/python3.8/site-packages/redbot/core/commands/context.py", line 93, in send
Sep 13 19:17:08 trainerdex-beta-0 python[2319040]:     return await super().send(content=content, **kwargs)
Sep 13 19:17:08 trainerdex-beta-0 python[2319040]:   File "/opt/DiscordBot/env/lib/python3.8/site-packages/discord/abc.py", line 895, in send
Sep 13 19:17:08 trainerdex-beta-0 python[2319040]:     await ret.delete(delay=delete_after)
Sep 13 19:17:08 trainerdex-beta-0 python[2319040]:   File "/opt/DiscordBot/env/lib/python3.8/site-packages/discord/ext/alternatives/silent_delete.py", line 14, in delete
Sep 13 19:17:08 trainerdex-beta-0 python[2319040]:     await _old_delete(delay=delay)
Sep 13 19:17:08 trainerdex-beta-0 python[2319040]: TypeError: delete() missing 1 required positional argument: 'self'
```

The `delete()` was called with `ctx.send("...", delete_after=30)`